export const states = [
  { id: '1', abbreviation: 'AL', name: 'Alabama', is_territory: '0' },
  { id: '2', abbreviation: 'AK', name: 'Alaska', is_territory: '0' },
  {
    id: '3',
    abbreviation: 'AS',
    name: '"American Samoa"',
    is_territory: '1',
  },
  { id: '4', abbreviation: 'AZ', name: 'Arizona', is_territory: '0' },
  { id: '5', abbreviation: 'AR', name: 'Arkansas', is_territory: '0' },
  {
    id: '6',
    abbreviation: 'CA',
    name: 'California',
    is_territory: '0',
  },
  { id: '7', abbreviation: 'CO', name: 'Colorado', is_territory: '0' },
  {
    id: '8',
    abbreviation: 'CT',
    name: 'Connecticut',
    is_territory: '0',
  },
  { id: '9', abbreviation: 'DE', name: 'Delaware', is_territory: '0' },
  {
    id: '10',
    abbreviation: 'DC',
    name: '"District of Columbia"',
    is_territory: '1',
  },
  { id: '11', abbreviation: 'US', name: 'Federal', is_territory: '1' },
  { id: '12', abbreviation: 'FL', name: 'Florida', is_territory: '0' },
  { id: '13', abbreviation: 'GA', name: 'Georgia', is_territory: '0' },
  { id: '14', abbreviation: 'GU', name: 'Guam', is_territory: '1' },
  { id: '15', abbreviation: 'HI', name: 'Hawaii', is_territory: '0' },
  { id: '16', abbreviation: 'ID', name: 'Idaho', is_territory: '0' },
  { id: '17', abbreviation: 'IL', name: 'Illinois', is_territory: '0' },
  { id: '18', abbreviation: 'IN', name: 'Indiana', is_territory: '0' },
  { id: '19', abbreviation: 'IA', name: 'Iowa', is_territory: '0' },
  { id: '20', abbreviation: 'KS', name: 'Kansas', is_territory: '0' },
  { id: '21', abbreviation: 'KY', name: 'Kentucky', is_territory: '0' },
  {
    id: '22',
    abbreviation: 'LA',
    name: 'Louisiana',
    is_territory: '0',
  },
  { id: '23', abbreviation: 'ME', name: 'Maine', is_territory: '0' },
  { id: '24', abbreviation: 'MD', name: 'Maryland', is_territory: '0' },
  {
    id: '25',
    abbreviation: 'MA',
    name: 'Massachusetts',
    is_territory: '0',
  },
  { id: '26', abbreviation: 'MI', name: 'Michigan', is_territory: '0' },
  {
    id: '27',
    abbreviation: 'MN',
    name: 'Minnesota',
    is_territory: '0',
  },
  {
    id: '28',
    abbreviation: 'MS',
    name: 'Mississippi',
    is_territory: '0',
  },
  { id: '29', abbreviation: 'MO', name: 'Missouri', is_territory: '0' },
  { id: '30', abbreviation: 'MT', name: 'Montana', is_territory: '0' },
  {
    id: '31',
    abbreviation: 'MP',
    name: '"N. Mariana Islands"',
    is_territory: '1',
  },
  { id: '32', abbreviation: 'NE', name: 'Nebraska', is_territory: '0' },
  { id: '33', abbreviation: 'NV', name: 'Nevada', is_territory: '0' },
  {
    id: '34',
    abbreviation: 'NH',
    name: '"New Hampshire"',
    is_territory: '0',
  },
  {
    id: '35',
    abbreviation: 'NJ',
    name: '"New Jersey"',
    is_territory: '0',
  },
  {
    id: '36',
    abbreviation: 'NM',
    name: '"New Mexico"',
    is_territory: '0',
  },
  {
    id: '37',
    abbreviation: 'NY',
    name: '"New York"',
    is_territory: '0',
  },
  {
    id: '38',
    abbreviation: 'NC',
    name: '"North Carolina"',
    is_territory: '0',
  },
  {
    id: '39',
    abbreviation: 'ND',
    name: '"North Dakota"',
    is_territory: '0',
  },
  { id: '40', abbreviation: 'OH', name: 'Ohio', is_territory: '0' },
  { id: '41', abbreviation: 'OK', name: 'Oklahoma', is_territory: '0' },
  { id: '42', abbreviation: 'OR', name: 'Oregon', is_territory: '0' },
  { id: '43', abbreviation: 'PW', name: 'Palau', is_territory: '1' },
  {
    id: '44',
    abbreviation: 'PA',
    name: 'Pennsylvania',
    is_territory: '0',
  },
  {
    id: '45',
    abbreviation: 'PR',
    name: '"Puerto Rico"',
    is_territory: '1',
  },
  {
    id: '46',
    abbreviation: 'RI',
    name: '"Rhode Island"',
    is_territory: '0',
  },
  {
    id: '47',
    abbreviation: 'SC',
    name: '"South Carolina"',
    is_territory: '0',
  },
  {
    id: '48',
    abbreviation: 'SD',
    name: '"South Dakota"',
    is_territory: '0',
  },
  {
    id: '49',
    abbreviation: 'TN',
    name: 'Tennessee',
    is_territory: '0',
  },
  { id: '50', abbreviation: 'TX', name: 'Texas', is_territory: '0' },
  { id: '51', abbreviation: 'UT', name: 'Utah', is_territory: '0' },
  { id: '52', abbreviation: 'VT', name: 'Vermont', is_territory: '0' },
  {
    id: '53',
    abbreviation: 'VI',
    name: '"Virgin Islands"',
    is_territory: '1',
  },
  { id: '54', abbreviation: 'VA', name: 'Virginia', is_territory: '0' },
  {
    id: '55',
    abbreviation: 'WA',
    name: 'Washington',
    is_territory: '0',
  },
  {
    id: '56',
    abbreviation: 'WV',
    name: '"West Virginia"',
    is_territory: '0',
  },
  {
    id: '57',
    abbreviation: 'WI',
    name: 'Wisconsin',
    is_territory: '0',
  },
  { id: '58', abbreviation: 'WY', name: 'Wyoming', is_territory: '0' },
  {
    id: '59',
    abbreviation: 'MH',
    name: '"Marshall Islands"',
    is_territory: '1',
  },
  {
    id: '60',
    abbreviation: 'FM',
    name: '"Federated States of Micronesia"',
    is_territory: '1',
  },
  { id: '' },
];
