import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import styles from '../../styles/Home.module.css';

const Program: NextPage = () => {
  const router = useRouter();
  const { pid } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Program</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Detail page for programs</h1>

        <p className={styles.description}>More info coming</p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Program;
