export const mockAPIResponse = {
  data: [
    {
      id: 1,
      fromSir: false,
      entireState: true,
      state: 39,
      stateObj: {
        id: 39,
        name: 'North Dakota',
        abbreviation: 'ND',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'ND02R',
      name: 'North Dakota Solar/Wind Easements and Laws',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p><b>Solar Policy</b></p><p>&#10;&#9;North Dakota's solar easement law is similar to those established by many other states. The law allows a property owner to obtain a solar easement from another property owner for the purpose of ensuring adequate exposure of a solar energy system to sunlight. A solar easement must include:</p>&#10;<ul>&#10;&#9;<li>&#10;&#9;&#9;The vertical and horizontal angles, expressed in degrees, at which the solar easement extends over the real property subject to the solar easement;</li>&#10;&#9;<li>&#10;&#9;&#9;Any terms, conditions, or both under which the solar easement is granted or will be terminated; and</li>&#10;&#9;<li>&#10;&#9;&#9;Any provisions for compensation of the owner of the property benefiting from the solar easement in the event of interference with the enjoyment of the solar easement or compensation of the owner of the property subject to the solar easement for maintaining the solar easement.</li>&#10;</ul>&#10;<p>&#10;&#9;Solar easements must be created in writing and are subject to the same conveyancing and instrument recording requirements as other easements.</p><p><b>Wind Policy</b></p><p>North Dakota allows property owners to grant an easement that ensures adequate exposure of a wind energy system to wind. The easement runs with the land benefited and burdened, and terminates upon the conditions stated in the easement. Easements are presumed to be abandoned if construction or operation has not begun within 36 months. The statute includes a process and timeline for termination of the easement in this event.</p><p>The statutes authorizing the creation of wind easements include several provisions to protect property owners. For example, a wind easement may not make the property owner liable for any property tax associated with the wind energy system or other equipment related to wind energy generation. In addition, the owner of the wind energy system must carry general liability insurance for damage or injury arising from the construction or operation of the wind energy facility project site.</p><p>North Dakota also provides guidelines for wind option agreements (contracts in which the owner of a property gives another the right to produce energy from wind power on that property at a fixed price within a time period of up to five years) and wind leases.</p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '08/02/2021',
      lastUpdated: 'August 2, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 2,
      fromSir: false,
      entireState: true,
      state: 4,
      stateObj: {
        id: 4,
        name: 'Arizona',
        abbreviation: 'AZ',
        is_territory: false,
      },
      type: 32,
      typeObj: {
        id: 32,
        name: 'Personal Tax Deduction',
        category: 1,
        categoryObj: {
          id: 1,
          name: 'Financial Incentive',
        },
      },
      category: 1,
      categoryObj: {
        id: 1,
        name: 'Financial Incentive',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'AZ10F',
      name: 'Qualifying Wood Stove Deduction',
      websiteUrl: '',
      administrator: '',
      fundingSource: '',
      budget: '',
      startDate: '1994-01-01',
      startDateDisplay: '01/01/1994',
      startDateText: '1/1/1994',
      endDate: '',
      endDateDisplay: '',
      endDateText: '',
      summary: `"<div>&#10;&#9;This incentive allows Arizona taxpayers to deduct the cost of converting an existing wood fireplace to a qualifying wood stove, a qualified wood fireplace, or a qualified gas-fired fireplace. The cost to purchase and install all necessary equipment is tax deductible, up to a maximum $500 deduction. Qualifying wood stoves and fireplaces must meet the standards of performance for new wood heaters manufactured after July 1990, or sold after July 1992 pursuant to <a href="http://www.ecfr.gov/cgi-bin/text-idx?SID=9e4ea365098310b8264e44cc81587b31&amp;mc=true&amp;node=sp40.7.60.aaa&amp;rgn=div6">40 Code of Federal Regulations part 60, subpart AAA</a>. This deduction is for taxable years after December 31, 1993.</div>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '06/26/2021',
      lastUpdated: 'June 26, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 3,
      fromSir: false,
      entireState: true,
      state: 24,
      stateObj: {
        id: 24,
        name: 'Maryland',
        abbreviation: 'MD',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'MD01R',
      name: 'Maryland Solar Easements & Rights Laws',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p>
	Maryland has a long-standing law protecting the rights of solar energy system owners. The original law prohibited restrictive land use covenants that imposed unreasonable limitations on the installation of solar collection panels on the roof or exterior walls of improvements and which became effective after July 1, 1980. (The grandfathering date was removed in 2008). This statute and its 2008 amendments do not apply to a restrictive covenant on historic property that is listed by the Maryland Inventory of Historic Properties or by the Maryland Register of Historic Properties.* Maryland also provides for the creation of easement agreements for a variety of purposes, including the &quot;preservation of exposure of solar energy devices.&quot; While similar provisions exist as standalone laws in some states, in Maryland they are included under the more general heading of conservation easements.<br />
	<br />
	The Maryland Real Property Code was amended in April 2008 by H.B. 117 to provide much more detailed protections for solar energy systems and to expand upon the required content of solar easement agreements. Under the new law (effective October 1, 2008) restrictions on use that act to significantly increase the cost of a solar collector system or significantly decrease its efficiency are prohibited. The definition of &quot;restrictions on use&quot; includes any covenant, restriction, or condition contained in a deed; declaration; contract; bylaws of a homeowners or condominium association; security instrument; and any other instrument affecting the transfer or sale of real property or interest in real property. The only condition for this protection is that the owner own or have rights for the exclusive use of the roof or exterior walls of a structure.<br />
	<br />
	In addition to the added detail, other notable changes to the law are: (1) the removal of the July 1, 1980 grandfathering date for existing restrictive covenants; and (2) the replacement of the term &quot;solar collection panels&quot; with &quot;solar collector systems&quot;. Solar collection systems are defined to include solar devices primarily used to collect, store, and distribute solar energy for electricity generation, space heating, space cooling, and water heating. This definition appears to include technologies such as passive solar space heating and solar pool heating.<br />
	<br />
	Under H.B. 117, the right of property owners to enter into solar easement agreements is affirmed. Written instruments for this purpose are required to contain a description of the dimensions of the easement (e.g., vertical and horizontal angles), restrictions on potential impairments (e.g., vegetation, structures, etc.), and terms for revision or termination.<br />
	<br />
	<br />
	<i>* While this law does not apply to historic properties, at least one local jurisdiction -- the Howard County Historic District Commission -- has developed guidelines&nbsp;for solar installations in historic districts.</i></p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/20/2021',
      lastUpdated: 'July 20, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 4,
      fromSir: false,
      entireState: false,
      state: 42,
      stateObj: {
        id: 42,
        name: 'Oregon',
        abbreviation: 'OR',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'OR02R',
      name: 'Oregon Solar and Wind Easements/Rights Laws & Local Option Solar Rights Law',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p><span>Oregon has several laws that protect access to solar and wind resources and the use of solar energy systems. Oregon's solar access laws date back to 1979 and state that no person conveying or contracting to convey a property title can include provisions that prohibit the use of solar energy systems on the property.</span><span> Any provisions that prohibit the use of solar energy systems are void and unenforceable. </span><span>Solar energy systems are defined broadly to include anything that uses solar radiation for heating, cooling, or electrical energy.  In June 2011, this law was expanded upon with the passage of HB 3516.  This legislation clarifies that in zones where residential and commercial structures are allowed uses, solar photovoltaic (PV) and solar thermal systems are explicitly allowed as a permitted use. The law was further expanded in 2017 with the passage of </span><a href="https://olis.leg.state.or.us/liz/2017R1/Downloads/MeasureDocument/HB2111/A-Engrossed">HB 2111</a><span>. The legislation voids any provisions, declarations, or bylaws of a planned community which prohibit installation and use of solar panels. </span><br/></p><p>&#10;&#9;<br/><b>Solar Easements:</b></p><p></p><p><span>Oregon's solar easement law was enacted in 1979; the wind easement law was enacted in 1981.</span></p><p>Prohibition against installation of solar panels are void and unenforceable. However, a homeowners association may adopt and enforce a provision that imposes reasonable size, placement or aesthetic requirements for the installation or use of solar panels</p><p><b>Requirements For Creation:</b></p><ul><li>A legal description of the real property benefited and burdened by the easement; and a description of the solar energy easement sufficient to determine the space over the burdened property which must remain unobstructed by means that shall include, but not be limited to: a sun chart showing the plotted skyline, including vegetation and structures from the perspective of the center of the lower edge of the collector surface, and a drawing showing the size and location of the collector surface being protected and its orientation with respect to true south; or a description of the solar envelope sufficient to determine the space over the burdened property that must remain unobstructed.</li><li>The instrument creating a solar energy easement or any other access right to sunlight shall be recordable under ORS 93.710. The instrument shall be recorded in the chains of title of the benefited and burdened properties as a transfer of the easement or access right from the owner of the burdened property to the owner of the benefited property.</li><li>When an instrument creating a solar energy easement is issued by a city or otherwise requires approval from a city, the instrument shall be attested to and contain the original signature of a city official in addition to the descriptions and chart required under subsection (1) of this section.</li><li>An instrument creating a solar energy easement shall be indexed when recorded by the name of the city and the names of all parties claiming any interest in the real property benefited or burdened by the easement.</li></ul><p><br/></p>&#10;&#9;<b>Solar Access:</b><p></p><p>Oregon state law also allows municipalities and local authorities to establish solar access laws. Access laws are intended to protect solar access to the south face of buildings during solar heating hours, taking into account existing development, vegetation, and planned uses. The local ordinances may include standards for orientation of new streets and lots, placement and height of new buildings, and the placement of new trees on public property. City and county laws are generally designed to protect south-facing roof space for active solar energy systems such as solar electric and solar hot water panels, as opposed to daylighting and passive solar heating that require southern exposure to a building's wall.</p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/27/2021',
      lastUpdated: 'July 27, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 6,
      fromSir: false,
      entireState: false,
      state: 2,
      stateObj: {
        id: 2,
        name: 'Alaska',
        abbreviation: 'AK',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'AK01R',
      name: 'Alaska Solar Easements',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p>
	Alaska&#39;s solar easement provisions are similar to those in many other states. They do not create an automatic right to sunlight. Rather, they allow parties to voluntarily enter into solar easement contracts for the purpose of ensuring adequate exposure of a solar energy system.</p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/19/2021',
      lastUpdated: 'July 19, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 7,
      fromSir: false,
      entireState: false,
      state: 16,
      stateObj: {
        id: 16,
        name: 'Idaho',
        abbreviation: 'ID',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'ID02R',
      name: 'Idaho Solar Easements & Access Laws',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p>In 2019, Idaho passed HB 158, which provides that a homeowner’s association may not limit or prohibit installation of solar panels or collectors on any property rooftop or structure within its jurisdiction. Homeowners associations may, however, enforce reasonable rules regarding the appearance of the panels. The provisions only apply to rooftops that are owned, controlled, and maintained by the homeowner.</p><p>Idaho law also allows for solar easements. Similar to laws in other states, Idaho's solar easement provision does not create an automatic right to sunlight. Rather, the law allows parties to enter into solar easement contracts voluntarily for the purpose of ensuring adequate exposure of sunlight to a solar-energy system. <span>The easement is transferred with the property title. </span></p><p><br/></p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/19/2021',
      lastUpdated: 'July 19, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 8,
      fromSir: false,
      entireState: true,
      state: 20,
      stateObj: {
        id: 20,
        name: 'Kansas',
        abbreviation: 'KS',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'KS01R',
      name: 'Kansas Solar Easement Laws',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p><span>Parties may voluntarily enter into solar easement contracts for the purpose of ensuring adequate exposure of a solar energy system. An easement must be expressed in writing and recorded with the register of deeds for that county.</span><br/></p><p></p><p>The written agreement must contain a description of the airspace in question and any term and/or conditions under which the solar easement is granted or terminated.</p><p></p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/20/2021',
      lastUpdated: 'July 20, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 10,
      fromSir: false,
      entireState: true,
      state: 13,
      stateObj: {
        id: 13,
        name: 'Georgia',
        abbreviation: 'GA',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'GA01R',
      name: 'Georgia Solar Easement Laws',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p>&#10;&#9;In determining that the use of solar energy &#34;can help reduce the nation's reliance upon imported fuels,&#34; Georgia encourages the development of solar-energy systems. Accordingly, under Georgia's Solar Easements Act of 1978, easements may be established to allow owners of solar-energy systems to negotiate for assurance of continued access to sunlight. Any easement must be created in writing and is subject to the same requirements as all other legal easements. The easement must contain:</p>&#10;<ul>&#10;&#9;<li>&#10;&#9;&#9;A description of the airspace affected by the easement</li>&#10;&#9;<li>&#10;&#9;&#9;Any terms and/or conditions under which the easement is granted or will be terminated</li>&#10;</ul>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/20/2021',
      lastUpdated: 'July 20, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 11,
      fromSir: false,
      entireState: true,
      state: 21,
      stateObj: {
        id: 21,
        name: 'Kentucky',
        abbreviation: 'KY',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'KY01R',
      name: 'Kentucky Solar Easements Laws',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p>
	In Kentucky, solar easements may be obtained for the purpose of ensuring access to direct sunlight. Easements must be expressed in writing and will become an interest in real property that may be acquired and transferred.</p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/20/2021',
      lastUpdated: 'July 20, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
    {
      id: 13,
      fromSir: false,
      entireState: false,
      state: 46,
      stateObj: {
        id: 46,
        name: 'Rhode Island',
        abbreviation: 'RI',
        is_territory: false,
      },
      type: 44,
      typeObj: {
        id: 44,
        name: 'Solar/Wind Access Policy',
        category: 2,
        categoryObj: {
          id: 2,
          name: 'Regulatory Policy',
        },
      },
      category: 2,
      categoryObj: {
        id: 2,
        name: 'Regulatory Policy',
      },
      sector: 1,
      sectorObj: {
        id: 1,
        name: 'State',
        active: true,
      },
      code: 'RI02R',
      name: 'Rhode Island Solar Easement Laws',
      websiteUrl: '',
      administrator: null,
      fundingSource: null,
      budget: null,
      startDate: '',
      startDateDisplay: null,
      startDateText: null,
      endDate: '',
      endDateDisplay: null,
      endDateText: null,
      summary: `"<p>&#10;&#9;Rhode Island allows property owners to establish solar easements in the same manner and with the same effect as a conveyance of an interest in real property. Solar easements must be created in writing. </p><p>In general, they must include: </p><p></p><ol><li><span>A description of the real property involved, </span></li><li><span>A description of the angles and three-dimensional space involved; </span></li><li><span>The terms under which the easement is granted or may be terminated, and</span></li><li><span>Any provisions for compensation of either property owner.</span></li></ol><p></p>&#10;<p>&#10;&#9;In addition, the state’s local zoning ordinances must address access to air and light, views, and solar access.</p>"`,
      published: 'Yes',
      parameterSets: [],
      updatedTs: '07/20/2021',
      lastUpdated: 'July 20, 2021',
      createdTs: '01/01/2000',
      additionalTechnologies: null,
    },
  ],
  meta: {
    total: 2592,
    limit: 10,
    offset: 0,
    tag: 'programs',
  },
  draw: null,
  recordsTotal: 2592,
  recordsFiltered: 2592,
};
