import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Programs.module.css';
import { ProgramItem } from '../components/programItem/ProgramItem';
import { useRouter } from 'next/router';
import { getResultsWithFilters, PAGE_SIZE } from '../utils';
import { ActionButton } from '../components/actionButton/ActionButton';

export async function getServerSideProps(context: any) {
  const queryParams = context.query;
  const programs = await getResultsWithFilters(queryParams);
  return {
    props: {
      programs,
    },
  };
}

const Programs: NextPage = ({ programs }: any) => {
  const router = useRouter();
  const data = programs.data;
  const total = programs.recordsTotal;
  const query = router.query;
  const currentPage = Number(query.page) || 1;
  return (
    <div className={styles.container}>
      <Head>
        <title>Programs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ul>
          {data?.map((program: any, i: number) => (
            <ProgramItem program={program} key={i} />
          ))}
        </ul>
        <div className={styles.buttonContainer}>
          <ActionButton
            disabled={currentPage === 1}
            onClick={() => {
              const updatedQueryParams = { ...query, page: currentPage - 1 };
              router.push({
                pathname: router.pathname,
                query: updatedQueryParams,
              });
            }}
          >
            Previous page
          </ActionButton>
          <ActionButton
            disabled={(currentPage + 1) * PAGE_SIZE > total}
            onClick={() => {
              const updatedQueryParams = { ...query, page: currentPage + 1 };
              router.push({
                pathname: router.pathname,
                query: updatedQueryParams,
              });
            }}
          >
            Next page
          </ActionButton>
        </div>
      </main>
    </div>
  );
};

export default Programs;
