import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { SurveySelect } from "../components/SurveySelect";

const Survey: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Survey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>LOGO</h1>
        <h4>breadcrumbs</h4>
        <SurveySelect
          title={"this is a title"}
          label={"label"}
          options={[{ label:'test option', value: 'TEST_OPTION' }, { label:'test option 1', value: 'TEST_OPTION1' }, { label:'test option 2', value: 'TEST_OPTION2' }]}
          trailingText={"trailing"}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Survey;
